### ISSUE TITLE
Support for EU Endpoint

### ISSUE THREAD

**Issue by paavo** [adilbaig/pagerduty#8]
Looks like the API Endpoint is hardcoded. 
Like this I can't use this to contact the EU Endpoint available at https://events.eu.pagerduty.com/v2/enqueue

**Comment by adilbaig** [comment]
Thanks for asking. Yes, the fact that `*Event()->send()` is hardcoded is not ideal to me. A proper solution would combine the `*Event` classes and `PagerDutyHttpConnection` into one. That refactor is not on my timeline atm, even though I think it's fully justified.

Atm, it's possible is to use the `PagerDutyHttpConnection()->send()` method. [See method here](https://github.com/adilbaig/pagerduty/blob/master/src/PagerDuty/Http/PagerDutyHttpConnection.php#L319). Here's a sample for your use-case:

```php
use \PagerDuty\TriggerEvent;
use \PagerDuty\Http\PagerDutyHttpConnection;

    $event = new TriggerEvent(...);

    // create a custom proxy connection
    $url = 'https://events.eu.pagerduty.com/v2/enqueue';
    $connection = new PagerDutyHttpConnection($url);
    
    // send event through proxy
    $connection->send($event);
```
